# Generated by Django 5.0.dev20230119053428 on 2023-01-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsQuestion',
            fields=[
                ('question_text', models.ImageField(upload_to='PhysicsQuestions')),
                ('question_viewed_count', models.IntegerField()),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('question_answer', models.ImageField(upload_to='PhysicsQuestions')),
            ],
        ),
    ]
