# Generated by Django 5.0.dev20230119053428 on 2023-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.ImageField(upload_to='Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.ImageField(upload_to='Questions'),
        ),
    ]
